# Mac OSX build
# Prerequisite: brew install portaudio
CFLAGS  = -arch x86_64 -Wall -fPIC -O2 -I/usr/local/include $(OPTS)
LDFLAGS = -arch x86_64 -L/usr/local/lib -lpthread -lportaudio -framework CoreAudio -framework AudioToolbox -framework AudioUnit -framework Carbon

EXECUTABLE ?= squeezelite-osx

include Makefile
