OPTS = -DFFMPEG -DOPUS -DRESAMPLE -DVISEXPORT -DDSD -DIR -DGPIO -DRPI -DSSL -DNO_SSLSYM -DLINKALL -I/usr/include -I/usr/include/opus -I/usr/include/alac -I/usr/local/include -s -mcpu=cortex-a72 -mtune=cortex-a72 

LDFLAGS=-L/usr/lib -L/usr/local/lib -s -lgomp -ldl

include Makefile
