OPTS = -DFFMPEG -DRESAMPLE -DGPIO -DUSE_SSL -DNO_SSLSYM
CPPFLAGS = -I/usr/local/include -I/usr/local/include/portaudio2
LDFLAGS = -L/usr/local/lib -L/usr/local/lib/portaudio2 -lportaudio -lssl -lcrypto -lm

include Makefile
