#!/bin/bash
make -f Makefile.rpi clean
make -f Makefile.rpi OPTS="-DLINKALL -DDSD -DVISEXPORT -DRESAMPLE -DIR -DGPIO -DRPI -I./include" LDFLAGS="/usr/lib/arm-linux-gnueabihf/libFLAC.a /usr/lib/arm-linux-gnueabihf/libvorbisfile.a /usr/lib/arm-linux-gnueabihf/libvorbis.a /usr/lib/arm-linux-gnueabihf/libogg.a /usr/lib/arm-linux-gnueabihf/libmad.a /usr/lib/arm-linux-gnueabihf/libfaad.a /usr/lib/arm-linux-gnueabihf/libmpg123.a /usr/lib/arm-linux-gnueabihf/libsoxr.a $HOME/source/picoreplayer/tcz/lirc/liblirc_client.a /usr/lib/gcc/arm-linux-gnueabihf/4.9/libgomp.a lib/libwiringPi.a -lpthread -ldl -lrt -lm -lasound"

strip squeezelite-rpi
mv squeezelite-rpi squeezelite-armv6hf-noffmpeg

make -f Makefile.rpi clean
make -f Makefile.rpi OPTS="-DLINKALL -DFFMPEG -DDSD -DVISEXPORT -DRESAMPLE -DIR -DGPIO -DRPI -I./include" LDFLAGS="/usr/lib/arm-linux-gnueabihf/libFLAC.a /usr/lib/arm-linux-gnueabihf/libvorbisfile.a /usr/lib/arm-linux-gnueabihf/libvorbis.a /usr/lib/arm-linux-gnueabihf/libogg.a /usr/lib/arm-linux-gnueabihf/libmad.a /usr/lib/arm-linux-gnueabihf/libfaad.a /usr/lib/arm-linux-gnueabihf/libmpg123.a lib/libswscale.a lib/libavdevice.a lib/libavformat.a lib/libavcodec.a lib/libswresample.a lib/libavutil.a /usr/lib/arm-linux-gnueabihf/libsoxr.a $HOME/source/picoreplayer/tcz/lirc/liblirc_client.a /usr/lib/gcc/arm-linux-gnueabihf/4.9/libgomp.a lib/libwiringPi.a /usr/lib/arm-linux-gnueabihf/libz.a -lpthread -ldl -lrt -lm -lasound"

strip squeezelite-rpi
mv squeezelite-rpi squeezelite-armv6hf-ffmpeg

