#!/bin/bash
# Use gcc 3.4
export PATH="/usr/gnu/bin:/usr/bin:/usr/sbin:/sbin"
rm squeezelite squeezelite-sada
startdir=`pwd`
cp -pr lib lib.orig
cp -pr include include.orig
svn co svn://ib/source/squeezeslave/trunk/squeezeslave/lib/portaudio || return 1
cd portaudio
make -f Makefile.solaris clean || return 1
make -f Makefile.solaris || return 1
ginstall -m644 libportaudio.a $startdir/lib/libportaudio.a
ginstall -m644 pa_common/portaudio.h $startdir/include/portaudio.h
cd $startdir || return 1
make -f Makefile.sun clean
make -f Makefile.sun || return 1
strip squeezelite-sun
mv squeezelite-sun squeezelite-sada
rm -rf lib
rm -rf include
mv lib.orig lib
mv include.orig include

cp -pr lib lib.orig
cp -pr include include.orig
cd portaudio
make -f Makefile.solaris clean || return 1
make -f Makefile.openindiana clean || return 1
make -f Makefile.openindiana || return 1
ginstall -m644 libportaudio.a $startdir/lib/libportaudio.a
ginstall -m644 pa_common/portaudio.h $startdir/include/portaudio.h
cd $startdir || return 1
rm -rf portaudio || return 1
make -f Makefile.sun clean
make -f Makefile.sun || return 1
strip squeezelite-sun
mv squeezelite-sun squeezelite
rm -rf lib
rm -rf include
mv lib.orig lib
mv include.orig include

