#!/bin/bash
make -f Makefile.x86_64 clean
make -f Makefile.x86_64
mv squeezelite-x86_64 squeezelite-x86_64-keep
make -f Makefile.x86_64 clean
patch -p0 -i scripts/portaudio-osx-10.4-i386.patch || exit 1
make -f Makefile.i386 clean
make -f Makefile.i386
svn revert main.c output_pa.c
mv squeezelite-x86_64-keep squeezelite-x86_64
strip squeezelite-x86_64
strip squeezelite-i386
lipo -create squeezelite-i386 squeezelite-x86_64 -output squeezelite
sudo cp squeezelite-i386 squeezelite-x86_64 squeezelite pkg/opt/squeezelite/bin/
make -f Makefile.x86_64 clean
make -f Makefile.i386 clean
