#!/bin/bash
make -f Makefile.ppc clean
make -f Makefile.ppc
mv squeezelite-ppc squeezelite-ppc-keep
make -f Makefile.ppc clean
make -f Makefile.ppc64 clean
make -f Makefile.ppc64
mv squeezelite-ppc-keep squeezelite-ppc
strip squeezelite-ppc
strip squeezelite-ppc64
lipo -create squeezelite-ppc squeezelite-ppc64 -output squeezelite
make -f Makefile.ppc64 clean
make -f Makefile.ppc clean
