#!/bin/bash
# https://trac.ffmpeg.org/wiki/CompilationGuide/MSVC

CYGDRIVE=/cygdrive

if [ -d $CYGDRIVE ]; then
	WINROOT=$CYGDRIVE/c
else
	WINROOT=/c
fi

export PATH=$WINROOT/Program\ Files/Microsoft\ Visual\ Studio\ 9.0/VC/bin:$WINROOT/Program\ Files/Microsoft\ Visual\ Studio\ 9.0/Common7/IDE:$WINROOT/Program\ Files/Microsoft\ SDKs/Windows/v6.0A/bin:$PATH
echo "PATH=$PATH"
export CL="/D_WIN32_WINNT=0x0501 /DWINVER=0x0501"
echo "CL=$CL"
export INCLUDE="C:\\Program Files\\Microsoft Visual Studio 9.0\\VC\\include;C:\\Program Files\\Microsoft SDKs\\Windows\\v6.0A\\Include"
echo "INCLUDE=$INCLUDE"
export LINK="/OPT:NOREF"
echo "LINK=$LINK"
export LIB="C:\\Program Files\\Microsoft Visual Studio 9.0\\VC\\lib;C:\\Program Files\\Microsoft SDKs\\Windows\\v6.0A\\Lib"
echo "LIB=$LIB"

make distclean

./configure \
    --prefix=$WINROOT \
    --toolchain=msvc \
    --disable-debug \
    --disable-avdevice \
    --disable-avfilter \
    --disable-swscale \
    --disable-swresample \
    --disable-ffmpeg \
    --disable-ffplay \
    --disable-ffserver \
    --disable-ffprobe \
    --disable-network \
    --disable-muxers \
    --disable-demuxers \
    --disable-hwaccels \
    --enable-rdft \
    --enable-demuxer=asf \
    --enable-demuxer=mov \
    --disable-bsfs \
    --disable-filters \
    --disable-parsers \
    --disable-protocols \
    --enable-protocol=file \
    --enable-protocol=pipe \
    --enable-protocol=cache \
    --disable-indevs \
    --disable-outdevs \
    --disable-encoders \
    --disable-decoders \
    --enable-decoder=alac \
    --enable-decoder=mjpeg \
    --enable-decoder=mjpegb \
    --enable-decoder=wmalossless \
    --enable-decoder=wmapro \
    --enable-decoder=wmav1 \
    --enable-decoder=wmav2 \
    --enable-decoder=wmavoice \
    --enable-runtime-cpudetect \
    --disable-shared \
    --enable-static \
    --disable-iconv \
    --disable-postproc \
    --disable-sdl \
    --disable-doc \
    --disable-podpages \
    --enable-gpl \
    --enable-version3 \
    --disable-x11grab \
    --disable-xlib \
    --disable-zlib \
    --disable-bzlib \
    --disable-dxva2 \
    --disable-fontconfig \
    --disable-libass \
    --disable-libbluray \
    --disable-libfreetype \
    --disable-libgsm \
    --disable-libmodplug \
    --disable-libmp3lame \
    --disable-libopencore_amrnb \
    --disable-libopencore_amrwb \
    --disable-libopenjpeg \
    --disable-libopus \
    --disable-libpulse \
    --disable-librtmp \
    --disable-libschroedinger \
    --disable-libspeex \
    --disable-libtheora \
    --disable-libv4l2 \
    --disable-libvorbis \
    --disable-libvpx \
    --disable-libx264 \
    --disable-libxvid \
    --disable-libxcb \
    --disable-libxcb-shm \
    --disable-libxcb-xfixes \
    --disable-libxcb-shape \
    --disable-vdpau

if [ ! -d pkg ]; then
        mkdir pkg
else
        rm -rf pkg
        mkdir pkg
fi

sed -i 's/HAVE_DIRECT_H 0/HAVE_DIRECT_H 1/g' config.h
sed -i 's/HAVE_IO_H 0/HAVE_IO_H 1/g' config.h
sed -i 's/HAVE_MALLOC_H 0/HAVE_MALLOC_H 1/g' config.h
sed -i 's/^#endif/#define snprintf _snprintf\n#endif/g' config.h

make || exit 1
make DESTDIR=`pwd`/pkg install-headers
make DESTDIR=`pwd`/pkg install-libs

rm _CL_*
