#!/bin/bash
export CFLAGS="-s -O3 -isysroot /Developer/SDKs/MacOSX10.7.sdk -arch x86_64"
export CPPFLAGS="${CFLAGS}"
export CXXFLAGS="${CFLAGS}"
export LDFLAGS="-Wl,-syslibroot,/Developer/SDKs/MacOSX10.7.sdk -arch x86_64 -mmacosx-version-min=10.7"

./configure \
    --prefix=/opt/squeezelite \
    --disable-debug \
    --disable-avdevice \
    --disable-avfilter \
    --disable-swscale \
    --disable-swresample \
    --disable-ffmpeg \
    --disable-ffplay \
    --disable-ffserver \
    --disable-ffprobe \
    --disable-network \
    --disable-muxers \
    --disable-demuxers \
    --disable-hwaccels \
    --enable-rdft \
    --enable-demuxer=asf \
    --enable-demuxer=mov \
    --disable-bsfs \
    --disable-filters \
    --disable-parsers \
    --disable-protocols \
    --enable-protocol=file \
    --enable-protocol=pipe \
    --enable-protocol=cache \
    --disable-indevs \
    --disable-outdevs \
    --disable-encoders \
    --disable-decoders \
    --enable-decoder=alac \
    --enable-decoder=mjpeg \
    --enable-decoder=mjpegb \
    --enable-decoder=wmalossless \
    --enable-decoder=wmapro \
    --enable-decoder=wmav1 \
    --enable-decoder=wmav2 \
    --enable-decoder=wmavoice \
    --enable-runtime-cpudetect \
    --disable-shared \
    --enable-static \
    --disable-iconv \
    --disable-postproc \
    --disable-sdl \
    --disable-doc \
    --disable-podpages \
    --enable-gpl \
    --enable-version3 \
    --disable-x11grab \
    --disable-xlib \
    --disable-zlib \
    --disable-bzlib \
    --disable-dxva2 \
    --disable-fontconfig \
    --disable-libass \
    --disable-libbluray \
    --disable-libfreetype \
    --disable-libgsm \
    --disable-libmodplug \
    --disable-libmp3lame \
    --disable-libopencore_amrnb \
    --disable-libopencore_amrwb \
    --disable-libopenjpeg \
    --disable-libopus \
    --disable-libpulse \
    --disable-librtmp \
    --disable-libschroedinger \
    --disable-libspeex \
    --disable-libtheora \
    --disable-libv4l2 \
    --disable-libvorbis \
    --disable-libvpx \
    --disable-libx264 \
    --disable-libxvid \
    --disable-libxcb \
    --disable-libxcb-shm \
    --disable-libxcb-xfixes \
    --disable-libxcb-shape \
    --disable-vdpau \
    --extra-ldflags=-Wl,-rpath,/opt/squeezelite/lib

if [ ! -d pkg ]; then
        mkdir pkg
else
        rm -rf pkg
        mkdir pkg
fi

make || return 1
make DESTDIR=`pwd`/pkg install-headers
make DESTDIR=`pwd`/pkg install-libs

