#!/bin/bash
startdir=`pwd`
mv lib lib.orig
mv include include.orig
svn co svn://ib/source/squeezeslave/trunk/squeezeslave/lib/portaudio || return 1
cd portaudio
make -f Makefile.linux26 clean || return 1
make -f Makefile.linux26 || return 1
install -m755 -d $startdir/lib
install -m755 -d $startdir/include
install -m644 libportaudio.a $startdir/lib/libportaudio.a
install -m644 pa_common/portaudio.h $startdir/include/portaudio.h
cd $startdir || return 1
rm -rf portaudio || return 1
make -f Makefile.paoss clean
make -f Makefile.paoss OPTS="-DLINKALL -DFFMPEG -DDSD -DVISEXPORT -DRESAMPLE -DIR -I/usr/local/include" LDFLAGS="-L/usr/local/lib /usr/lib/i386-linux-gnu/libFLAC.a /usr/lib/i386-linux-gnu/libvorbisfile.a /usr/lib/i386-linux-gnu/libvorbis.a /usr/lib/i386-linux-gnu/libogg.a /usr/lib/libmad.a /usr/lib/i386-linux-gnu/libfaad.a /usr/lib/i386-linux-gnu/libmpg123.a /usr/local/lib/libswscale.a /usr/local/lib/libavdevice.a /usr/local/lib/libavformat.a /usr/local/lib/libavcodec.a /usr/local/lib/libswresample.a /usr/local/lib/libavutil.a /usr/lib/libsoxr.a /usr/lib/liblirc_client.a /usr/lib/gcc/i486-linux-gnu/4.7/libgomp.a /usr/lib/i386-linux-gnu/libz.a -L./lib -lportaudio -lpthread -ldl -lrt -lm" || return 1
strip squeezelite-oss
rm -rf lib
rm -rf include
mv lib.orig lib
mv include.orig include
