#!/bin/bash
make -f Makefile.rpi clean
make -f Makefile.rpi OPTS="-DLINKALL -DDSD -DVISEXPORT -DRESAMPLE -DIR -DGPIO -Iinclude" LDFLAGS="-Llib /usr/lib/arm-linux-gnueabihf/libFLAC.a /usr/lib/arm-linux-gnueabihf/libvorbisfile.a /usr/lib/arm-linux-gnueabihf/libvorbis.a /usr/lib/arm-linux-gnueabihf/libogg.a /usr/lib/libmad.a /usr/lib/arm-linux-gnueabihf/libfaad.a /usr/lib/arm-linux-gnueabihf/libmpg123.a lib/libsoxr.a $HOME/source/tcz/lirc/liblirc_client.a /usr/lib/gcc/arm-linux-gnueabihf/4.6/libgomp.a -lpthread -ldl -lrt -lm -lasound"

strip squeezelite-rpi
mv squeezelite-rpi squeezelite-armv6hf-noffmpeg

make -f Makefile.rpi clean
make -f Makefile.rpi OPTS="-DLINKALL -DFFMPEG -DDSD -DVISEXPORT -DRESAMPLE -DIR -DGPIO -Iinclude" LDFLAGS="-Llib /usr/lib/arm-linux-gnueabihf/libFLAC.a /usr/lib/arm-linux-gnueabihf/libvorbisfile.a /usr/lib/arm-linux-gnueabihf/libvorbis.a /usr/lib/arm-linux-gnueabihf/libogg.a /usr/lib/libmad.a /usr/lib/arm-linux-gnueabihf/libfaad.a /usr/lib/arm-linux-gnueabihf/libmpg123.a lib/libswscale.a lib/libavdevice.a lib/libavformat.a lib/libavcodec.a lib/libswresample.a lib/libavutil.a lib/libsoxr.a $HOME/source/tcz/lirc/liblirc_client.a /usr/lib/gcc/arm-linux-gnueabihf/4.6/libgomp.a /usr/lib/arm-linux-gnueabihf/libz.a -lpthread -ldl -lrt -lm -lasound"

strip squeezelite-rpi
mv squeezelite-rpi squeezelite-armv6hf-ffmpeg

