#!/bin/ksh
#
PKGNAME=SUNWsqueezelite
startdir=$HOME/source/squeezelite
SVNVER=`cd $startdir; (svnversion | gsed -e 's/[MS]//g')`
VERSION=1.6.4.${SVNVER}
SAVEDIR=`pwd`
HOSTNAME=`uname -n`

if [ -d $startdir/pkg ]; then
    rm -rf pkg
fi

cd $startdir
mkdir -p pkg/squeezelite/bin
mkdir -p pkg/squeezelite/lib

cp -p /usr/sfw/lib/libgcc_s.so.1 pkg/squeezelite/lib

cp -p lib/libsoxr.so.0 pkg/squeezelite/lib
setrpath -f pkg/squeezelite/lib/libsoxr.so.0 "/opt/squeezelite/lib:/usr/ccs/lib:/lib:/usr/lib:/usr/sfw/lib" || return 1

cp -p squeezelite pkg/squeezelite/bin/
cp -p squeezelite-sada pkg/squeezelite/bin/
cp -p scripts/squeezelite.sh pkg/squeezelite/bin
gsed -i 's:^export LD_LIBRARY_PATH=\$INSTALL_DIR\/lib:#export LD_LIBRARY_PATH=\$INSTALL_DIR\/lib:' pkg/squeezelite/bin/squeezelite.sh
gsed -i 's:^\$INSTALL_DIR/bin/squeezelite \$DEV \$:\$INSTALL_DIR/bin/squeezelite-sada \$DEV \$:' pkg/squeezelite/bin/squeezelite.sh

cd $startdir/pkg/squeezelite/bin
ln -s squeezelite-oi squeezelite

cd $startdir/pkg

echo "CLASSES=none" > pkginfo
echo "BASEDIR=/opt" >> pkginfo
echo "LANG=C" >> pkginfo
echo "TZ=Canada/Eastern" >> pkginfo
echo "PATH=/sbin:/usr/sbin:/usr/bin:/usr/sadm/install/bin" >> pkginfo
echo "OAMBASE=/usr/sadm/sysadm" >> pkginfo
echo "ARCH=sparc" >> pkginfo
echo "PKG=${PKGNAME}" >> pkginfo
echo "NAME=squeezelite - non-gui client for the logitech streaming media server" >> pkginfo
echo "VERSION=${VERSION},REV=`date '+%Y.%m.%d'`" >> pkginfo
echo "CATEGORY=application" >> pkginfo
echo "VENDOR=https://github.com/ralph-irving packaged by Ralph Irving" >> pkginfo
echo "HOTLINE=https://github.com/ralph-irving/squeezelite/issues" >> pkginfo
echo "EMAIL=ralph_irving@hotmail.com" >> pkginfo
echo "PSTAMP=${HOSTNAME%%.*}`date +'%Y%m%d%H%M%S'`" >> pkginfo
echo "PKGSAV=/var/sadm/pkg/${PKGNAME}/save" >> pkginfo

echo 'i pkginfo=pkginfo' > prototype
id | sed 's/uid=[0-9]*(//' | sed 's/).*//' > uid.tmp
id | sed 's/.*(//' | sed 's/)//' > gid.tmp
find . \! -name pkginfo -a \! -name prototype | \
pkgproto | sed "s/ `cat uid.tmp`/ root/" | \
sed "s| `cat gid.tmp`| bin|" | \
sed "s|f none uid.tmp 0644 root bin||" | \
sed "s|f none gid.tmp 0644 root bin||" \
>> prototype
rm -f uid.tmp gid.tmp

pkgmk -o -r `pwd` -a `uname -m` -v ${VERSION}
cd /var/spool/pkg
echo "1" | pkgtrans -s `pwd` ${HOME}/source/packages/${PKGNAME}-${VERSION}.pkg
rm -rf ${PKGNAME}
cd ${SAVEDIR}
